"""Platform templates and profile configuration logic"""

import random
from datetime import datetime


# Platform templates (imported from tegufox-config logic)
# NOTE: Mixed property key format per Tegufox config schema:
#   - navigator.*, screen.* use DOTS (.)
#   - canvas:*, AudioContext:*, webGl:* use COLONS (:)
PLATFORM_TEMPLATES = {
    "ebay-seller": {
        "desc": "eBay seller profile optimized for account longevity",
        "config": {
            "navigator.userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/135.0",
            "navigator.platform": "Win32",
            "navigator.hardwareConcurrency": 8,
            "screen.width": 1920,
            "screen.height": 1080,
            "screen.colorDepth": 24,
            "AudioContext:sampleRate": 48000,
            "AudioContext:maxChannelCount": 2,
            "canvas:seed": None,
            # WebGL auto-generated by Tegufox based on OS
        },
    },
    "amazon-fba": {
        "desc": "Amazon FBA seller profile",
        "config": {
            "navigator.userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15) Gecko/20100101 Firefox/135.0",
            "navigator.platform": "MacIntel",
            "navigator.hardwareConcurrency": 10,
            "screen.width": 1470,
            "screen.height": 956,
            "screen.colorDepth": 30,
            "AudioContext:sampleRate": 48000,
            "canvas:seed": None,
            # WebGL auto-generated by Tegufox
        },
    },
    "etsy-shop": {
        "desc": "Etsy shop owner profile",
        "config": {
            "navigator.userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/135.0",
            "navigator.platform": "Win32",
            "navigator.hardwareConcurrency": 12,
            "screen.width": 2560,
            "screen.height": 1440,
            "screen.colorDepth": 24,
            "AudioContext:sampleRate": 44100,
            "canvas:seed": None,
            # WebGL auto-generated by Tegufox
        },
    },
    "generic": {
        "desc": "Generic buyer profile",
        "config": {
            "navigator.userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/135.0",
            "navigator.platform": "Win32",
            "screen.width": 1920,
            "screen.height": 1080,
        },
    },
}


def generate_random_seed():
    """Generate random seed for canvas/audio"""
    return random.randint(1000000, 9999999999)


def create_profile_data(platform, name):
    """Create a new profile payload from template (core logic)."""

    if platform not in PLATFORM_TEMPLATES:
        raise ValueError(f"Unknown platform: {platform}")

    template = PLATFORM_TEMPLATES[platform]
    config = template["config"].copy()

    # Generate random seeds
    if "canvas:seed" in config and config["canvas:seed"] is None:
        config["canvas:seed"] = generate_random_seed()
    if "audio:seed" in config and config["audio:seed"] is None:
        config["audio:seed"] = generate_random_seed()

    # Create profile metadata
    profile = {
        "name": name,
        "platform": platform,
        "created": datetime.now().isoformat(),
        "description": template["desc"],
        "config": config,
        "metadata": {"version": "1.0", "tegufox_version": "0.1.0"},
    }

    return profile
