#!/usr/bin/env python3
"""
Tegufox Profile Manager - GUI Application
Modern PyQt6 interface for managing browser profiles
"""

import sys
import json
import subprocess
import random
from pathlib import Path
from datetime import datetime
from PyQt6.QtWidgets import (
    QApplication,
    QMainWindow,
    QWidget,
    QVBoxLayout,
    QHBoxLayout,
    QLabel,
    QPushButton,
    QListWidget,
    QListWidgetItem,
    QTabWidget,
    QLineEdit,
    QComboBox,
    QSlider,
    QSpinBox,
    QTextEdit,
    QGroupBox,
    QGridLayout,
    QStackedWidget,
    QFrame,
    QScrollArea,
    QMessageBox,
    QFileDialog,
)
from PyQt6.QtCore import Qt, QSize, pyqtSignal
from PyQt6.QtGui import QIcon, QFont, QPalette, QColor


class DarkPalette:
    """Dark theme colors matching the image"""

    BACKGROUND = "#1e1e2e"  # Main background
    SIDEBAR = "#181825"  # Sidebar background
    CARD = "#262637"  # Card/panel background
    ACCENT = "#89b4fa"  # Blue accent
    RED = "#f38ba8"  # Red accent
    TEXT = "#e0e6ff"  # Primary text - brighter for better contrast
    TEXT_DIM = "#bac2de"  # Dim text - still readable
    BORDER = "#313244"  # Borders
    HOVER = "#313244"  # Hover state


# Platform templates (imported from tegufox-config logic)
# NOTE: Mixed property key format per Camoufox properties.json:
#   - navigator.*, screen.* use DOTS (.)
#   - canvas:*, AudioContext:*, webGl:* use COLONS (:)
PLATFORM_TEMPLATES = {
    "ebay-seller": {
        "desc": "eBay seller profile optimized for account longevity",
        "config": {
            "navigator.userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/135.0",
            "navigator.platform": "Win32",
            "navigator.hardwareConcurrency": 8,
            "screen.width": 1920,
            "screen.height": 1080,
            "screen.colorDepth": 24,
            "AudioContext:sampleRate": 48000,
            "AudioContext:maxChannelCount": 2,
            "canvas:seed": None,
            # WebGL auto-generated by Camoufox based on OS
        },
    },
    "amazon-fba": {
        "desc": "Amazon FBA seller profile",
        "config": {
            "navigator.userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15) Gecko/20100101 Firefox/135.0",
            "navigator.platform": "MacIntel",
            "navigator.hardwareConcurrency": 10,
            "screen.width": 1470,
            "screen.height": 956,
            "screen.colorDepth": 30,
            "AudioContext:sampleRate": 48000,
            "canvas:seed": None,
            # WebGL auto-generated by Camoufox
        },
    },
    "etsy-shop": {
        "desc": "Etsy shop owner profile",
        "config": {
            "navigator.userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/135.0",
            "navigator.platform": "Win32",
            "navigator.hardwareConcurrency": 12,
            "screen.width": 2560,
            "screen.height": 1440,
            "screen.colorDepth": 24,
            "AudioContext:sampleRate": 44100,
            "canvas:seed": None,
            # WebGL auto-generated by Camoufox
        },
    },
    "generic": {
        "desc": "Generic buyer profile",
        "config": {
            "navigator.userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/135.0",
            "navigator.platform": "Win32",
            "screen.width": 1920,
            "screen.height": 1080,
        },
    },
}


def generate_random_seed():
    """Generate random seed for canvas/audio"""
    return random.randint(1000000, 9999999999)


def create_profile_data(platform, name, output_dir="profiles"):
    """Create a new profile from template (core logic)"""

    if platform not in PLATFORM_TEMPLATES:
        raise ValueError(f"Unknown platform: {platform}")

    template = PLATFORM_TEMPLATES[platform]
    config = template["config"].copy()

    # Generate random seeds
    if "canvas:seed" in config and config["canvas:seed"] is None:
        config["canvas:seed"] = generate_random_seed()
    if "audio:seed" in config and config["audio:seed"] is None:
        config["audio:seed"] = generate_random_seed()

    # Create profile metadata
    profile = {
        "name": name,
        "platform": platform,
        "created": datetime.now().isoformat(),
        "description": template["desc"],
        "config": config,
        "metadata": {"version": "1.0", "tegufox_version": "0.1.0"},
    }

    # Save profile
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    profile_file = output_path / f"{name}.json"
    with open(profile_file, "w") as f:
        json.dump(profile, f, indent=2)

    return profile_file, profile


class SidebarButton(QPushButton):
    """Styled sidebar button"""

    def __init__(self, text, icon_text="", parent=None):
        super().__init__(text, parent)
        self.icon_text = icon_text
        self.setFixedHeight(45)
        self.setStyleSheet(f"""
            QPushButton {{
                background-color: transparent;
                color: {DarkPalette.TEXT_DIM};
                border: none;
                border-radius: 8px;
                padding: 12px 16px;
                text-align: left;
                font-size: 14px;
            }}
            QPushButton:hover {{
                background-color: {DarkPalette.HOVER};
                color: {DarkPalette.TEXT};
            }}
            QPushButton:checked {{
                background-color: {DarkPalette.ACCENT};
                color: white;
            }}
        """)
        self.setCheckable(True)


class ProfileCard(QFrame):
    """Profile card widget"""

    clicked = pyqtSignal(str)  # Emit profile name when clicked
    delete_requested = pyqtSignal(str)  # Emit profile name when delete clicked
    launch_requested = pyqtSignal(str)  # Emit profile name when launch clicked

    def __init__(self, profile_data, parent=None):
        super().__init__(parent)
        self.profile_data = profile_data
        self.setup_ui()

    def setup_ui(self):
        self.setFrameStyle(QFrame.Shape.StyledPanel)
        self.setStyleSheet(f"""
            QFrame {{
                background-color: {DarkPalette.CARD};
                border: 1px solid {DarkPalette.BORDER};
                border-radius: 10px;
                margin: 6px;
            }}
            QFrame:hover {{
                background-color: {DarkPalette.HOVER};
                border-color: {DarkPalette.ACCENT};
            }}
        """)
        self.setFixedHeight(160)
        self.setVisible(True)

        # Main layout
        layout = QVBoxLayout(self)
        layout.setContentsMargins(20, 16, 20, 16)
        layout.setSpacing(12)

        # Header row: name + delete button
        header_layout = QHBoxLayout()
        header_layout.setSpacing(12)

        name = self.profile_data.get("name", "Unnamed")
        name_label = QLabel(name)
        name_label.setStyleSheet("color: #ffffff; font-size: 16px; font-weight: 600;")
        header_layout.addWidget(name_label)
        header_layout.addStretch()

        delete_btn = QPushButton("🗑️")
        delete_btn.setFixedSize(36, 36)
        delete_btn.setStyleSheet(f"""
            QPushButton {{
                background-color: rgba(243, 139, 168, 0.15);
                color: {DarkPalette.RED};
                border: none;
                border-radius: 6px;
                font-size: 16px;
            }}
            QPushButton:hover {{
                background-color: rgba(243, 139, 168, 0.25);
            }}
        """)
        delete_btn.clicked.connect(lambda: self.delete_requested.emit(name))
        header_layout.addWidget(delete_btn)

        layout.addLayout(header_layout)

        # Info row: platform, date, config in horizontal layout
        info_layout = QHBoxLayout()
        info_layout.setSpacing(16)

        # Platform badge
        platform = self.profile_data.get("platform", "unknown")
        platform_badge = QLabel(platform)
        platform_badge.setStyleSheet(f"""
            color: {DarkPalette.ACCENT};
            font-size: 12px;
            font-weight: 500;
            background-color: rgba(137, 180, 250, 0.15);
            border-radius: 4px;
            padding: 4px 10px;
        """)
        info_layout.addWidget(platform_badge)

        # Date
        created = self.profile_data.get("created", "")
        if created:
            try:
                dt = datetime.fromisoformat(created)
                created_str = dt.strftime("%b %d")
            except:
                created_str = created[:10]
            date_label = QLabel(f"📅 {created_str}")
            date_label.setStyleSheet(f"color: {DarkPalette.TEXT_DIM}; font-size: 11px;")
            info_layout.addWidget(date_label)

        # Config count
        config_count = len(self.profile_data.get("config", {}))
        config_label = QLabel(f"⚙️ {config_count} configs")
        config_label.setStyleSheet(f"color: {DarkPalette.TEXT_DIM}; font-size: 11px;")
        info_layout.addWidget(config_label)

        info_layout.addStretch()
        layout.addLayout(info_layout)

        # Launch button
        launch_btn = QPushButton("🚀 Launch Browser")
        launch_btn.setFixedHeight(44)
        launch_btn.setStyleSheet(f"""
            QPushButton {{
                background-color: {DarkPalette.ACCENT};
                color: white;
                border: none;
                border-radius: 8px;
                font-size: 14px;
                font-weight: 600;
            }}
            QPushButton:hover {{
                background-color: #7aa2f7;
            }}
            QPushButton:pressed {{
                background-color: #6b92e6;
            }}
        """)
        launch_btn.clicked.connect(lambda: self.launch_requested.emit(name))
        layout.addWidget(launch_btn)

    def mousePressEvent(self, event):
        # Don't emit clicked if clicking on buttons
        if event.button() == Qt.MouseButton.LeftButton:
            # Check if click is on a button by checking cursor
            if self.childAt(event.pos()) is None or not isinstance(
                self.childAt(event.pos()), QPushButton
            ):
                self.clicked.emit(self.profile_data.get("name", ""))
        super().mousePressEvent(event)


class CreateProfileWidget(QWidget):
    """Create profiles tab content"""

    profile_created = pyqtSignal()  # Signal to notify when profile is created

    def __init__(self, parent=None):
        super().__init__(parent)
        # Store widget references
        self.name_input = None
        self.platform_combo = None
        self.count_slider = None
        self.group_combo = None
        self.setup_ui()

    def setup_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(40, 40, 40, 40)
        layout.setSpacing(20)

        # Title
        title = QLabel("Create Profiles")
        title.setStyleSheet(
            f"color: {DarkPalette.TEXT}; font-size: 28px; font-weight: bold;"
        )
        layout.addWidget(title)

        # Tab widget for different sections
        tabs = QTabWidget()
        tabs.setStyleSheet(f"""
            QTabWidget::pane {{
                border: 1px solid {DarkPalette.BORDER};
                background-color: {DarkPalette.CARD};
                border-radius: 8px;
            }}
            QTabBar::tab {{
                background-color: {DarkPalette.BACKGROUND};
                color: {DarkPalette.TEXT_DIM};
                border: none;
                padding: 12px 24px;
                border-top-left-radius: 8px;
                border-top-right-radius: 8px;
                margin-right: 4px;
            }}
            QTabBar::tab:selected {{
                background-color: {DarkPalette.CARD};
                color: {DarkPalette.TEXT};
            }}
            QTabBar::tab:hover {{
                background-color: {DarkPalette.HOVER};
            }}
        """)

        # Overview tab
        overview_widget = self.create_overview_tab()
        tabs.addTab(overview_widget, "Overview")

        # Network tab
        network_widget = self.create_network_tab()
        tabs.addTab(network_widget, "Network")

        # Hardware tab
        hardware_widget = self.create_hardware_tab()
        tabs.addTab(hardware_widget, "Hardware")

        layout.addWidget(tabs)

        # Action buttons
        button_layout = QHBoxLayout()
        button_layout.addStretch()

        cancel_btn = QPushButton("Cancel")
        cancel_btn.setStyleSheet(f"""
            QPushButton {{
                background-color: transparent;
                color: {DarkPalette.TEXT_DIM};
                border: 1px solid {DarkPalette.BORDER};
                border-radius: 8px;
                padding: 12px 32px;
                font-size: 14px;
            }}
            QPushButton:hover {{
                background-color: {DarkPalette.HOVER};
            }}
        """)
        button_layout.addWidget(cancel_btn)

        create_btn = QPushButton("Create Profile")
        create_btn.setStyleSheet(f"""
            QPushButton {{
                background-color: {DarkPalette.RED};
                color: white;
                border: none;
                border-radius: 8px;
                padding: 12px 32px;
                font-size: 14px;
                font-weight: bold;
            }}
            QPushButton:hover {{
                background-color: #f5748c;
            }}
        """)
        create_btn.clicked.connect(self.create_profile)
        button_layout.addWidget(create_btn)

        layout.addLayout(button_layout)

    def create_overview_tab(self):
        """Overview tab with bulk creation"""
        widget = QWidget()
        layout = QVBoxLayout(widget)
        layout.setContentsMargins(20, 20, 20, 20)
        layout.setSpacing(20)

        # Bulk creation section
        bulk_group = QGroupBox("Bulk creation")
        bulk_group.setStyleSheet(f"""
            QGroupBox {{
                color: {DarkPalette.TEXT};
                border: 1px solid {DarkPalette.BORDER};
                border-radius: 8px;
                margin-top: 12px;
                padding: 20px;
            }}
            QGroupBox::title {{
                subcontrol-origin: margin;
                left: 12px;
                padding: 0 8px;
            }}
        """)

        bulk_layout = QVBoxLayout()

        # Profile count slider
        count_layout = QHBoxLayout()
        count_label = QLabel("1 profiles")
        count_label.setStyleSheet(f"color: {DarkPalette.ACCENT}; font-weight: bold;")
        count_layout.addWidget(count_label)
        bulk_layout.addLayout(count_layout)

        self.count_slider = QSlider(Qt.Orientation.Horizontal)
        self.count_slider.setMinimum(1)
        self.count_slider.setMaximum(30)
        self.count_slider.setValue(1)
        self.count_slider.setStyleSheet(f"""
            QSlider::groove:horizontal {{
                border: none;
                height: 4px;
                background: {DarkPalette.BORDER};
                border-radius: 2px;
            }}
            QSlider::handle:horizontal {{
                background: {DarkPalette.ACCENT};
                border: none;
                width: 16px;
                height: 16px;
                margin: -6px 0;
                border-radius: 8px;
            }}
            QSlider::sub-page:horizontal {{
                background: {DarkPalette.ACCENT};
                border-radius: 2px;
            }}
        """)
        self.count_slider.valueChanged.connect(
            lambda v: count_label.setText(f"{v} profiles")
        )
        bulk_layout.addWidget(self.count_slider)

        # Scale markers
        scale_layout = QHBoxLayout()
        for i in [1, 5, 10, 15, 20, 30]:
            label = QLabel(str(i))
            label.setStyleSheet(f"color: {DarkPalette.TEXT_DIM}; font-size: 11px;")
            scale_layout.addWidget(label)
            if i != 30:
                scale_layout.addStretch()
        bulk_layout.addLayout(scale_layout)

        bulk_group.setLayout(bulk_layout)
        layout.addWidget(bulk_group)

        # Profile details
        details_layout = QGridLayout()
        details_layout.setSpacing(16)

        # Group
        details_layout.addWidget(QLabel("Group"), 0, 0)
        self.group_combo = QComboBox()
        self.group_combo.addItems(
            ["Default", "eBay Sellers", "Amazon FBA", "Etsy Shops"]
        )
        self.group_combo.setStyleSheet(self.get_combo_style())
        details_layout.addWidget(self.group_combo, 0, 1)

        # Name
        name_label = QLabel("Name *")
        name_label.setStyleSheet(f"color: {DarkPalette.TEXT};")
        details_layout.addWidget(name_label, 0, 2)

        self.name_input = QLineEdit()
        self.name_input.setPlaceholderText("Profile name (e.g., seller-001)")
        self.name_input.setStyleSheet(self.get_input_style())
        details_layout.addWidget(self.name_input, 0, 3)

        # Platform selection
        details_layout.addWidget(QLabel("Platform *"), 1, 0)
        self.platform_combo = QComboBox()
        self.platform_combo.addItems(
            ["eBay Seller", "Amazon FBA", "Etsy Shop", "Generic"]
        )
        self.platform_combo.setStyleSheet(self.get_combo_style())
        details_layout.addWidget(self.platform_combo, 1, 1)

        # Browser Version
        details_layout.addWidget(QLabel("Browser Version"), 1, 2)
        browser_combo = QComboBox()
        browser_combo.addItems(["Firefox 135", "Firefox 134", "Firefox 133"])
        browser_combo.setStyleSheet(self.get_combo_style())
        details_layout.addWidget(browser_combo, 1, 3)

        layout.addLayout(details_layout)

        layout.addStretch()
        return widget

    def create_network_tab(self):
        """Network configuration tab"""
        widget = QWidget()
        layout = QVBoxLayout(widget)
        layout.setContentsMargins(20, 20, 20, 20)

        label = QLabel("Network settings will go here")
        label.setStyleSheet(f"color: {DarkPalette.TEXT_DIM};")
        layout.addWidget(label)
        layout.addStretch()

        return widget

    def create_hardware_tab(self):
        """Hardware spoofing tab"""
        widget = QWidget()
        layout = QVBoxLayout(widget)
        layout.setContentsMargins(20, 20, 20, 20)

        # Platform selection
        platform_layout = QHBoxLayout()
        platform_layout.addWidget(QLabel("Platform:"))

        platform_combo = QComboBox()
        platform_combo.addItems(["Windows 10", "Windows 11", "macOS", "Linux"])
        platform_combo.setStyleSheet(self.get_combo_style())
        platform_layout.addWidget(platform_combo)
        platform_layout.addStretch()

        layout.addLayout(platform_layout)

        # Screen resolution
        screen_group = QGroupBox("Screen Resolution")
        screen_group.setStyleSheet(f"color: {DarkPalette.TEXT};")
        screen_layout = QGridLayout()

        screen_layout.addWidget(QLabel("Width:"), 0, 0)
        width_spin = QSpinBox()
        width_spin.setRange(800, 7680)
        width_spin.setValue(1920)
        width_spin.setStyleSheet(self.get_input_style())
        screen_layout.addWidget(width_spin, 0, 1)

        screen_layout.addWidget(QLabel("Height:"), 1, 0)
        height_spin = QSpinBox()
        height_spin.setRange(600, 4320)
        height_spin.setValue(1080)
        height_spin.setStyleSheet(self.get_input_style())
        screen_layout.addWidget(height_spin, 1, 1)

        screen_group.setLayout(screen_layout)
        layout.addWidget(screen_group)

        layout.addStretch()
        return widget

    def get_combo_style(self):
        return f"""
            QComboBox {{
                background-color: {DarkPalette.BACKGROUND};
                color: {DarkPalette.TEXT};
                border: 1px solid {DarkPalette.BORDER};
                border-radius: 6px;
                padding: 8px 12px;
                min-width: 150px;
            }}
            QComboBox:hover {{
                border-color: {DarkPalette.ACCENT};
            }}
            QComboBox::drop-down {{
                border: none;
            }}
            QComboBox QAbstractItemView {{
                background-color: {DarkPalette.CARD};
                color: {DarkPalette.TEXT};
                selection-background-color: {DarkPalette.ACCENT};
            }}
        """

    def get_input_style(self):
        return f"""
            QLineEdit, QSpinBox {{
                background-color: {DarkPalette.BACKGROUND};
                color: {DarkPalette.TEXT};
                border: 1px solid {DarkPalette.BORDER};
                border-radius: 6px;
                padding: 8px 12px;
            }}
            QLineEdit:focus, QSpinBox:focus {{
                border-color: {DarkPalette.ACCENT};
            }}
        """

    def create_profile(self):
        """Create profile action"""
        # Get form values
        name = self.name_input.text().strip()
        if not name:
            QMessageBox.warning(
                self, "Validation Error", "Please enter a profile name."
            )
            return

        # Map platform UI text to template keys
        platform_map = {
            "eBay Seller": "ebay-seller",
            "Amazon FBA": "amazon-fba",
            "Etsy Shop": "etsy-shop",
            "Generic": "generic",
        }

        platform_text = self.platform_combo.currentText()
        platform = platform_map.get(platform_text, "generic")

        count = self.count_slider.value()

        try:
            created_files = []

            if count == 1:
                # Create single profile
                profile_file, profile_data = create_profile_data(platform, name)
                created_files.append(profile_file)
            else:
                # Bulk creation - append numbers
                for i in range(1, count + 1):
                    bulk_name = f"{name}-{i:03d}"
                    profile_file, profile_data = create_profile_data(
                        platform, bulk_name
                    )
                    created_files.append(profile_file)

            # Show success message
            msg = f"✅ Successfully created {len(created_files)} profile(s)!\n\n"
            msg += f"Platform: {platform_text}\n"
            msg += f"Location: profiles/\n\n"
            msg += "Files:\n"
            for f in created_files[:5]:  # Show first 5
                msg += f"  • {f.name}\n"

            if len(created_files) > 5:
                msg += f"  ... and {len(created_files) - 5} more"

            QMessageBox.information(self, "Success", msg)

            # Clear form
            self.name_input.clear()
            self.count_slider.setValue(1)

            # Emit signal to refresh profile list
            self.profile_created.emit()

        except Exception as e:
            QMessageBox.critical(self, "Error", f"Failed to create profile:\n{str(e)}")


class ProfilesListWidget(QWidget):
    """Profiles list view"""

    def __init__(self, parent=None):
        super().__init__(parent)
        print("🔧 ProfilesListWidget.__init__() called")
        self.profiles = []
        self.setup_ui()
        print("🔧 setup_ui() completed, calling load_profiles()")
        self.load_profiles()
        print("🔧 ProfilesListWidget initialization complete")

    def setup_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(40, 40, 40, 40)
        layout.setSpacing(20)

        # Header
        header_layout = QHBoxLayout()

        title = QLabel("Browser Profiles")
        title.setStyleSheet(
            f"color: {DarkPalette.TEXT}; font-size: 28px; font-weight: bold;"
        )
        header_layout.addWidget(title)

        header_layout.addStretch()

        # Refresh button
        refresh_btn = QPushButton("🔄 Refresh")
        refresh_btn.setStyleSheet(f"""
            QPushButton {{
                background-color: {DarkPalette.CARD};
                color: {DarkPalette.TEXT};
                border: 1px solid {DarkPalette.BORDER};
                border-radius: 8px;
                padding: 10px 20px;
                font-size: 14px;
            }}
            QPushButton:hover {{
                background-color: {DarkPalette.HOVER};
            }}
        """)
        refresh_btn.clicked.connect(self.refresh_profiles)
        header_layout.addWidget(refresh_btn)

        # Search
        search = QLineEdit()
        search.setPlaceholderText("Search profiles...")
        search.setStyleSheet(f"""
            QLineEdit {{
                background-color: {DarkPalette.CARD};
                color: {DarkPalette.TEXT};
                border: 1px solid {DarkPalette.BORDER};
                border-radius: 8px;
                padding: 10px 16px;
                min-width: 300px;
            }}
        """)
        header_layout.addWidget(search)

        layout.addLayout(header_layout)

        # Scroll area for profiles
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setStyleSheet(
            "QScrollArea { border: none; background-color: transparent; }"
        )

        self.scroll_widget = QWidget()
        self.scroll_widget.setStyleSheet(f"background-color: {DarkPalette.BACKGROUND};")
        self.profiles_layout = QVBoxLayout(self.scroll_widget)
        self.profiles_layout.setSpacing(16)
        self.profiles_layout.setContentsMargins(0, 0, 0, 0)
        self.profiles_layout.setAlignment(Qt.AlignmentFlag.AlignTop)  # Align to top

        scroll.setWidget(self.scroll_widget)
        layout.addWidget(scroll)

    def load_profiles(self):
        """Load profiles from disk"""
        profiles_dir = Path("profiles")
        if not profiles_dir.exists():
            print("❌ Profiles directory not found!")
            return

        count = 0
        for profile_file in profiles_dir.glob("*.json"):
            try:
                with open(profile_file) as f:
                    profile_data = json.load(f)
                    card = ProfileCard(profile_data)
                    card.clicked.connect(self.on_profile_clicked)
                    card.delete_requested.connect(self.on_profile_delete)
                    card.launch_requested.connect(self.on_profile_launch)
                    self.profiles_layout.addWidget(card)
                    count += 1
                    print(f"✅ Loaded profile card: {profile_data.get('name')}")
            except Exception as e:
                print(f"❌ Error loading {profile_file}: {e}")
                import traceback

                traceback.print_exc()

        self.profiles_layout.addStretch()
        print(f"✅ Total profiles loaded: {count}")

    def refresh_profiles(self):
        """Refresh profile list"""
        # Clear existing cards
        while self.profiles_layout.count():
            item = self.profiles_layout.takeAt(0)
            if item.widget():
                item.widget().deleteLater()

        # Reload profiles
        self.load_profiles()

    def on_profile_clicked(self, profile_name):
        """Handle profile card click"""
        # Load and show profile details
        profiles_dir = Path("profiles")
        profile_file = profiles_dir / f"{profile_name}.json"

        if profile_file.exists():
            with open(profile_file) as f:
                profile_data = json.load(f)

            # Format profile info
            info = f"Profile: {profile_name}\n\n"
            info += f"Platform: {profile_data.get('platform', 'unknown')}\n"
            info += f"Description: {profile_data.get('description', 'N/A')}\n"
            info += f"Created: {profile_data.get('created', 'N/A')}\n\n"
            info += "Configuration:\n"

            config = profile_data.get("config", {})
            for key, value in sorted(config.items())[:10]:  # Show first 10 keys
                info += f"  • {key}: {value}\n"

            if len(config) > 10:
                info += f"  ... and {len(config) - 10} more keys\n"

            QMessageBox.information(self, "Profile Details", info)

    def on_profile_delete(self, profile_name):
        """Handle profile deletion"""
        reply = QMessageBox.question(
            self,
            "Confirm Delete",
            f"Are you sure you want to delete profile '{profile_name}'?\n\nThis action cannot be undone.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
            QMessageBox.StandardButton.No,
        )

        if reply == QMessageBox.StandardButton.Yes:
            try:
                profiles_dir = Path("profiles")
                profile_file = profiles_dir / f"{profile_name}.json"

                if profile_file.exists():
                    profile_file.unlink()
                    QMessageBox.information(
                        self, "Success", f"Profile '{profile_name}' has been deleted."
                    )
                    self.refresh_profiles()
                else:
                    QMessageBox.warning(
                        self, "Error", f"Profile file not found: {profile_file}"
                    )
            except Exception as e:
                QMessageBox.critical(
                    self, "Error", f"Failed to delete profile:\n{str(e)}"
                )

    def on_profile_launch(self, profile_name):
        """Handle browser launch with profile"""
        try:
            profiles_dir = Path("profiles")
            profile_file = profiles_dir / f"{profile_name}.json"

            if not profile_file.exists():
                QMessageBox.warning(
                    self, "Error", f"Profile file not found: {profile_file}"
                )
                return

            # Load profile config
            with open(profile_file) as f:
                profile_data = json.load(f)

            config = profile_data.get("config", {})
            platform = profile_data.get("platform", "unknown")

            # Fix config format and filter invalid keys
            fixed_config = {}
            for key, value in config.items():
                # Skip WebGL keys - let Camoufox auto-generate
                if key.startswith("webGl:"):
                    continue

                # Convert navigator:* and screen:* to use dots
                if key.startswith("navigator:") or key.startswith("screen:"):
                    new_key = key.replace(":", ".")
                    fixed_config[new_key] = value
                else:
                    fixed_config[key] = value

            config = fixed_config

            # Show launching message
            QMessageBox.information(
                self,
                "Launching Browser",
                f"Launching Camoufox with profile '{profile_name}'...\n\n"
                f"Platform: {platform}\n"
                f"Config keys: {len(config)}\n\n"
                f"The browser will open in a new window.\n"
                f"Close this dialog to continue.",
            )

            # Launch browser in subprocess to not block GUI
            # Create a temporary script to launch the browser
            launch_script = f"""
import sys
import time
sys.path.insert(0, '{Path.cwd()}')
from camoufox.sync_api import Camoufox
import json

# Load config
with open('{profile_file}') as f:
    profile = json.load(f)
    raw_config = profile.get('config', {{}})

# Fix config format and filter invalid keys
config = {{}}
for key, value in raw_config.items():
    # Skip WebGL keys - let Camoufox auto-generate
    if key.startswith("webGl:"):
        print(f"⚠️  Skipping WebGL key: {{key}}")
        continue
        
    # Convert navigator:* and screen:* to use dots
    if key.startswith("navigator:") or key.startswith("screen:"):
        new_key = key.replace(":", ".")
        config[new_key] = value
        print(f"✓ Converted {{key}} → {{new_key}}")
    else:
        config[key] = value

print(f"🦊 Launching Camoufox with profile: {profile_name}")
print(f"Platform: {platform}")
print(f"Config keys: {{len(config)}}")

# Launch browser with config
try:
    with Camoufox(headless=False, config=config, i_know_what_im_doing=True) as browser:
        page = browser.new_page()
        page.goto("https://www.browserscan.net/bot-detection")
        print("✅ Browser launched! Close the browser window when done.")
        
        # Keep browser open - wait for user to close it
        while True:
            try:
                page.title()  # Check if page still exists
                time.sleep(1)
            except:
                break
except Exception as e:
    print(f"❌ Launch failed: {{e}}")
    import traceback
    traceback.print_exc()
"""

            # Write temporary launch script
            temp_script = Path("/tmp/tegufox_launch.py")
            with open(temp_script, "w") as f:
                f.write(launch_script)

            # Launch in background with output to terminal
            subprocess.Popen(
                [sys.executable, str(temp_script)],
                stdout=None,  # Output to terminal
                stderr=None,  # Errors to terminal
            )

        except Exception as e:
            QMessageBox.critical(
                self, "Launch Error", f"Failed to launch browser:\n{str(e)}"
            )


class TegufoxProfileManager(QMainWindow):
    """Main application window"""

    def __init__(self):
        super().__init__()
        self.setWindowTitle("Tegufox Profile Manager")
        self.setMinimumSize(1200, 800)
        self.setup_ui()
        self.apply_dark_theme()

    def setup_ui(self):
        """Setup main UI"""
        central_widget = QWidget()
        self.setCentralWidget(central_widget)

        main_layout = QHBoxLayout(central_widget)
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(0)

        # Sidebar
        sidebar = self.create_sidebar()
        main_layout.addWidget(sidebar)

        # Main content area
        self.content_stack = QStackedWidget()
        main_layout.addWidget(self.content_stack, 1)

        # Add pages
        self.home_page = QLabel("Home")
        self.home_page.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.home_page.setStyleSheet(f"color: {DarkPalette.TEXT}; font-size: 24px;")
        self.content_stack.addWidget(self.home_page)

        self.marketplace_page = QLabel("Marketplace")
        self.marketplace_page.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.marketplace_page.setStyleSheet(
            f"color: {DarkPalette.TEXT}; font-size: 24px;"
        )
        self.content_stack.addWidget(self.marketplace_page)

        self.orders_page = QLabel("Orders")
        self.orders_page.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.orders_page.setStyleSheet(f"color: {DarkPalette.TEXT}; font-size: 24px;")
        self.content_stack.addWidget(self.orders_page)

        # Profiles section
        self.profiles_list = ProfilesListWidget()
        self.content_stack.addWidget(self.profiles_list)

        self.create_profile_page = CreateProfileWidget()
        # Connect signal to refresh profiles list when new profile is created
        self.create_profile_page.profile_created.connect(
            self.profiles_list.refresh_profiles
        )
        self.content_stack.addWidget(self.create_profile_page)

        self.settings_page = QLabel("Settings")
        self.settings_page.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.settings_page.setStyleSheet(f"color: {DarkPalette.TEXT}; font-size: 24px;")
        self.content_stack.addWidget(self.settings_page)

    def create_sidebar(self):
        """Create sidebar with navigation"""
        sidebar = QFrame()
        sidebar.setFixedWidth(220)
        sidebar.setStyleSheet(f"background-color: {DarkPalette.SIDEBAR};")

        layout = QVBoxLayout(sidebar)
        layout.setContentsMargins(16, 24, 16, 24)
        layout.setSpacing(8)

        # Logo/Title with image
        logo_container = QWidget()
        logo_layout = QVBoxLayout(logo_container)
        logo_layout.setContentsMargins(0, 0, 0, 0)
        logo_layout.setSpacing(8)

        # Try to load logo image
        logo_label = QLabel()
        logo_path = Path(__file__).parent / "tegufox-tool.png"
        if logo_path.exists():
            from PyQt6.QtGui import QPixmap

            pixmap = QPixmap(str(logo_path))
            scaled_pixmap = pixmap.scaled(
                120,
                120,
                Qt.AspectRatioMode.KeepAspectRatio,
                Qt.TransformationMode.SmoothTransformation,
            )
            logo_label.setPixmap(scaled_pixmap)
            logo_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        else:
            logo_label.setText("🦊")
            logo_label.setStyleSheet(f"font-size: 48px;")
            logo_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        logo_layout.addWidget(logo_label)

        # Title
        title_label = QLabel("Tegufox")
        title_label.setStyleSheet(
            f"color: {DarkPalette.ACCENT}; font-size: 18px; font-weight: bold;"
        )
        title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        logo_layout.addWidget(title_label)

        layout.addWidget(logo_container)

        layout.addSpacing(20)

        # Navigation buttons
        self.nav_buttons = []

        home_btn = SidebarButton("Home", "🏠")
        home_btn.clicked.connect(lambda: self.switch_page(0))
        layout.addWidget(home_btn)
        self.nav_buttons.append(home_btn)

        marketplace_btn = SidebarButton("Marketplace", "🛒")
        marketplace_btn.clicked.connect(lambda: self.switch_page(1))
        layout.addWidget(marketplace_btn)
        self.nav_buttons.append(marketplace_btn)

        orders_btn = SidebarButton("Orders", "📋")
        orders_btn.clicked.connect(lambda: self.switch_page(2))
        layout.addWidget(orders_btn)
        self.nav_buttons.append(orders_btn)

        layout.addSpacing(12)

        # Profiles section
        profiles_label = QLabel("PROFILES")
        profiles_label.setStyleSheet(
            f"color: {DarkPalette.TEXT_DIM}; font-size: 11px; padding: 8px 16px;"
        )
        layout.addWidget(profiles_label)

        groups_btn = SidebarButton("Groups", "📁")
        layout.addWidget(groups_btn)
        self.nav_buttons.append(groups_btn)

        create_btn = SidebarButton("Create", "➕")
        create_btn.clicked.connect(lambda: self.switch_page(4))
        layout.addWidget(create_btn)
        self.nav_buttons.append(create_btn)

        local_btn = SidebarButton("Local", "💾")
        local_btn.clicked.connect(lambda: self.switch_page(3))
        layout.addWidget(local_btn)
        self.nav_buttons.append(local_btn)

        cloud_btn = SidebarButton("Cloud", "☁️")
        layout.addWidget(cloud_btn)
        self.nav_buttons.append(cloud_btn)

        tasks_btn = SidebarButton("Tasks", "✅")
        layout.addWidget(tasks_btn)
        self.nav_buttons.append(tasks_btn)

        layout.addStretch()

        # Settings at bottom
        settings_btn = SidebarButton("Settings", "⚙️")
        settings_btn.clicked.connect(lambda: self.switch_page(5))
        layout.addWidget(settings_btn)
        self.nav_buttons.append(settings_btn)

        return sidebar

    def switch_page(self, index):
        """Switch to page and update button states"""
        self.content_stack.setCurrentIndex(index)
        for i, btn in enumerate(self.nav_buttons):
            # Simple logic - you can improve this
            btn.setChecked(False)

    def apply_dark_theme(self):
        """Apply dark theme to application"""
        self.setStyleSheet(f"""
            QMainWindow {{
                background-color: {DarkPalette.BACKGROUND};
            }}
            QWidget {{
                background-color: {DarkPalette.BACKGROUND};
                color: {DarkPalette.TEXT};
            }}
            QLabel {{
                color: {DarkPalette.TEXT};
            }}
            QScrollBar:vertical {{
                background-color: {DarkPalette.BACKGROUND};
                width: 12px;
                border-radius: 6px;
            }}
            QScrollBar::handle:vertical {{
                background-color: {DarkPalette.BORDER};
                border-radius: 6px;
            }}
            QScrollBar::handle:vertical:hover {{
                background-color: {DarkPalette.TEXT_DIM};
            }}
        """)


def main():
    app = QApplication(sys.argv)

    # Set application-wide font
    font = QFont("SF Pro Display", 12)
    app.setFont(font)

    window = TegufoxProfileManager()
    window.show()

    sys.exit(app.exec())


if __name__ == "__main__":
    main()
