#!/usr/bin/env bash
# Regenerate Tegufox patches from the current source tree.
#
# Workflow: edit C++ in camoufox-source/camoufox-*/ → run this script →
# patches/tegufox/*.patch updated. Source dir stays disposable; patches
# are the single source of truth, tracked in this repo.
#
# Prerequisites:
#   - Source tree must have all Tegufox changes applied
#   - The 'camoufox-patched' git tag must exist (created by `make camoufox-dir`)
#
# Usage:
#   ./scripts/tegufox-generate-patches.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

FF_VERSION=$(grep "^version=" "$PROJECT_ROOT/camoufox-source/upstream.sh" | cut -d= -f2)
FF_RELEASE=$(grep "^release=" "$PROJECT_ROOT/camoufox-source/upstream.sh" | cut -d= -f2)
FF_SOURCE_DIR="$PROJECT_ROOT/camoufox-source/camoufox-${FF_VERSION}-${FF_RELEASE}"
PATCHES_DIR="$PROJECT_ROOT/patches/tegufox"

if [ ! -d "$FF_SOURCE_DIR" ]; then
    echo "Error: Firefox source not found at $FF_SOURCE_DIR" >&2
    exit 1
fi

cd "$FF_SOURCE_DIR"

if ! git rev-parse camoufox-patched >/dev/null 2>&1; then
    echo "Error: 'camoufox-patched' tag not found. Run 'make camoufox-dir' first." >&2
    exit 1
fi

# Manifest: each entry = "patch-name|space-separated-file-or-dir-paths".
# Order matches series file. Patch 09 (branding) handled separately due to binary files.
PATCH_MANIFEST=(
  "01-canvas-v2.patch|dom/canvas/TegufoxCanvasNoise.cpp dom/canvas/TegufoxCanvasNoise.h dom/canvas/CanvasRenderingContext2D.cpp dom/canvas/moz.build"
  "02-webgl-enhanced.patch|dom/canvas/TegufoxGPUProfiles.cpp dom/canvas/TegufoxGPUProfiles.h dom/canvas/ClientWebGLContext.cpp"
  "03-audio-context-v2.patch|dom/media/webaudio/TegufoxAudioNoise.cpp dom/media/webaudio/TegufoxAudioNoise.h dom/media/webaudio/AnalyserNode.cpp dom/media/webaudio/moz.build"
  "04-tls-ja3-ja4.patch|security/nss/lib/ssl/TegufoxTLSNoise.c security/nss/lib/ssl/TegufoxTLSNoise.h security/nss/lib/ssl/ssl3con.c security/nss/lib/ssl/manifest.mn security/nss/lib/ssl/ssl.gyp"
  "05-webrtc-ice.patch|dom/media/webrtc/jsep/JsepSessionImpl.cpp dom/media/webrtc/transport/third_party/nICEr/src/ice/ice_candidate.c dom/media/webrtc/transport/third_party/nICEr/src/ice/ice_ctx.c"
  "06-font-metrics-v2.patch|gfx/thebes/TegufoxFontNoise.cpp gfx/thebes/TegufoxFontNoise.h gfx/thebes/moz.build layout/style/GeckoBindings.cpp"
  "07-http2-settings.patch|netwerk/protocol/http/Http2Session.cpp netwerk/protocol/http/Http2Compression.cpp"
  "08-navigator-v2.patch|dom/base/Navigator.cpp"
  "11-dns-force-doh.patch|netwerk/dns/TRRService.cpp netwerk/dns/TRRServiceBase.cpp"
  "12-timezone-native-spoof.patch|intl/components/src/TimeZone.cpp"
)

# Branding patch: STATIC. Not regenerated by this script because GNU patch
# (used by tegufox-apply-patches.sh) ignores GIT binary patch blocks — so
# regenerating from the working tree would lose the icon binaries that the
# original patch ships. The text portion (configure.sh, brand.dtd/ftl/properties,
# moz.configure) DOES get applied; icons are cosmetic, no anti-detect impact.
# Edit 09-branding.patch by hand if branding text changes.
BRANDING_PATCH="09-branding.patch"
BRANDING_PATHS="browser/branding/camoufox browser/moz.configure"

# Stage all changes (including untracked Tegufox*.cpp/.h) so git diff --cached sees them.
git add -A

echo "Generating Tegufox patches → $PATCHES_DIR"
echo ""

# All files we expect to cover. Used for end-of-run validation.
ALL_COVERED_FILES=""

for entry in "${PATCH_MANIFEST[@]}"; do
    name="${entry%%|*}"
    files="${entry#*|}"
    echo "  $name"
    # shellcheck disable=SC2086
    git diff camoufox-patched --cached -- $files > "$PATCHES_DIR/$name"
    ALL_COVERED_FILES="$ALL_COVERED_FILES $files"
done

# Branding patch is hand-maintained; only register coverage so validation
# below doesn't flag branding files as "missed".
echo "  $BRANDING_PATCH (static — not regenerated)"
ALL_COVERED_FILES="$ALL_COVERED_FILES $BRANDING_PATHS"

echo ""

# Validation: every modified/new file in working tree must belong to exactly one patch.
# Anything in working tree but NOT in manifest = silent drop, which is the bug we are
# fixing. Exit non-zero so CI catches it.
# Build markers and other runtime artifacts that live in the source tree but
# are not patches. Add to this list when new non-patch markers appear.
NON_PATCH_MARKERS='.tegufox-patched'

COVERED_LIST=$(echo "$ALL_COVERED_FILES" | tr ' ' '\n' | sort -u | sed '/^$/d')
WORKING_TREE_LIST=$(git diff camoufox-patched --cached --name-only | grep -vxF "$NON_PATCH_MARKERS" | sort -u)

UNCOVERED=""
while IFS= read -r f; do
    [ -z "$f" ] && continue
    # Match file directly OR if it lives under a covered directory prefix.
    matched=0
    while IFS= read -r covered; do
        [ -z "$covered" ] && continue
        if [ "$f" = "$covered" ] || [ "${f#"$covered"/}" != "$f" ]; then
            matched=1
            break
        fi
    done <<< "$COVERED_LIST"
    if [ "$matched" = "0" ]; then
        UNCOVERED="$UNCOVERED$f"$'\n'
    fi
done <<< "$WORKING_TREE_LIST"

TOTAL_FILES=$(echo "$WORKING_TREE_LIST" | grep -c . || true)
echo "Total files modified vs camoufox-patched: $TOTAL_FILES"

if [ -n "$UNCOVERED" ]; then
    echo ""
    echo "ERROR: files modified in source tree but NOT covered by any patch manifest:" >&2
    echo "$UNCOVERED" >&2
    echo "" >&2
    echo "Add these paths to the matching patch entry in PATCH_MANIFEST." >&2
    exit 1
fi

echo "Regenerated ${#PATCH_MANIFEST[@]} patches; $BRANDING_PATCH preserved; every modified file is covered."
